<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="9" time="174.210" timestamp="2025-08-22T13:12:29.807193" hostname="dut7358"><testcase classname="test.distributed.tensor.parallel.test_tp_style.TensorParallelStyleTest" name="test_colwise_parallel_embedding" time="16.446" /><testcase classname="test.distributed.tensor.parallel.test_tp_style.TensorParallelStyleTest" name="test_colwise_parallel_style" time="28.876" /><testcase classname="test.distributed.tensor.parallel.test_tp_style.TensorParallelStyleTest" name="test_prepare_module_input" time="15.844" /><testcase classname="test.distributed.tensor.parallel.test_tp_style.TensorParallelStyleTest" name="test_prepare_module_input_multiple_inputs" time="15.439" /><testcase classname="test.distributed.tensor.parallel.test_tp_style.TensorParallelStyleTest" name="test_prepare_module_kwargs_input" time="15.731" /><testcase classname="test.distributed.tensor.parallel.test_tp_style.TensorParallelStyleTest" name="test_prepare_module_output" time="16.336" /><testcase classname="test.distributed.tensor.parallel.test_tp_style.TensorParallelStyleTest" name="test_rowwise_parallel_embedding" time="28.571" /><testcase classname="test.distributed.tensor.parallel.test_tp_style.TensorParallelStyleTest" name="test_rowwise_parallel_style" time="29.274" /><testcase classname="test.distributed.tensor.parallel.test_tp_style.TensorParallelStyleTest" name="test_sequence_parallel_style" time="5.425"><failure message="RuntimeError: Process 1 exited with error code 10 and exception:&#10;Traceback (most recent call last):&#10;  File &quot;/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py&quot;, line 864, in run_test&#10;    getattr(self, test_name)()&#10;  File &quot;/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py&quot;, line 718, in wrapper&#10;    fn()&#10;  File &quot;/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py&quot;, line 3226, in wrapper&#10;    method(*args, **kwargs)&#10;  File &quot;/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/distributed/_tensor/common_dtensor.py&quot;, line 491, in wrapper&#10;    raise e&#10;  File &quot;/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/distributed/_tensor/common_dtensor.py&quot;, line 488, in wrapper&#10;    func(self, *args, **kwargs)  # type: ignore[misc]&#10;  File &quot;/home/jenkins/actions-runner/_work/torch-xpu-ops/pytorch/test/distributed/tensor/parallel/test_tp_style.py&quot;, line 385, in test_sequence_parallel_style&#10;    self.assertEqual(sharded_out.full_tensor(), output)&#10;  File &quot;/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py&quot;, line 4181, in assertEqual&#10;    raise error_metas.pop()[0].to_error(  # type: ignore[index]&#10;AssertionError: Tensor-likes are not close!&#10;&#10;Mismatched elements: 3840 / 7680 (50.0%)&#10;Greatest absolute difference: 3.7509000301361084 at index (13, 8, 0) (up to 1e-05 allowed)&#10;Greatest relative difference: 3634.929931640625 at index (2, 12, 2) (up to 1.3e-06 allowed)&#10;&#10;To execute this test, run the following from the base repo dir:&#10;    PYTORCH_TEST_WITH_SLOW=1 python test/distributed/tensor/parallel/test_tp_style.py TensorParallelStyleTest.test_sequence_parallel_style&#10;&#10;This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0&#10;&#10;Process 2 exited with error code 10 and exception:&#10;Traceback (most recent call last):&#10;  File &quot;/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py&quot;, line 864, in run_test&#10;    getattr(self, test_name)()&#10;  File &quot;/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py&quot;, line 718, in wrapper&#10;    fn()&#10;  File &quot;/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py&quot;, line 3226, in wrapper&#10;    method(*args, **kwargs)&#10;  File &quot;/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/distributed/_tensor/common_dtensor.py&quot;, line 491, in wrapper&#10;    raise e&#10;  File &quot;/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/distributed/_tensor/common_dtensor.py&quot;, line 488, in wrapper&#10;    func(self, *args, **kwargs)  # type: ignore[misc]&#10;  File &quot;/home/jenkins/actions-runner/_work/torch-xpu-ops/pytorch/test/distributed/tensor/parallel/test_tp_style.py&quot;, line 385, in test_sequence_parallel_style&#10;    self.assertEqual(sharded_out.full_tensor(), output)&#10;  File &quot;/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py&quot;, line 4181, in assertEqual&#10;    raise error_metas.pop()[0].to_error(  # type: ignore[index]&#10;AssertionError: Tensor-likes are not close!&#10;&#10;Mismatched elements: 3840 / 7680 (50.0%)&#10;Greatest absolute difference: 3.7509000301361084 at index (13, 8, 0) (up to 1e-05 allowed)&#10;Greatest relative difference: 3634.929931640625 at index (2, 12, 2) (up to 1.3e-06 allowed)&#10;&#10;To execute this test, run the following from the base repo dir:&#10;    PYTORCH_TEST_WITH_SLOW=1 python test/distributed/tensor/parallel/test_tp_style.py TensorParallelStyleTest.test_sequence_parallel_style&#10;&#10;This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0&#10;&#10;Process 3 exited with error code 10 and exception:&#10;Traceback (most recent call last):&#10;  File &quot;/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py&quot;, line 864, in run_test&#10;    getattr(self, test_name)()&#10;  File &quot;/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py&quot;, line 718, in wrapper&#10;    fn()&#10;  File &quot;/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py&quot;, line 3226, in wrapper&#10;    method(*args, **kwargs)&#10;  File &quot;/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/distributed/_tensor/common_dtensor.py&quot;, line 491, in wrapper&#10;    raise e&#10;  File &quot;/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/distributed/_tensor/common_dtensor.py&quot;, line 488, in wrapper&#10;    func(self, *args, **kwargs)  # type: ignore[misc]&#10;  File &quot;/home/jenkins/actions-runner/_work/torch-xpu-ops/pytorch/test/distributed/tensor/parallel/test_tp_style.py&quot;, line 385, in test_sequence_parallel_style&#10;    self.assertEqual(sharded_out.full_tensor(), output)&#10;  File &quot;/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py&quot;, line 4181, in assertEqual&#10;    raise error_metas.pop()[0].to_error(  # type: ignore[index]&#10;AssertionError: Tensor-likes are not close!&#10;&#10;Mismatched elements: 3840 / 7680 (50.0%)&#10;Greatest absolute difference: 3.7509000301361084 at index (13, 8, 0) (up to 1e-05 allowed)&#10;Greatest relative difference: 3634.929931640625 at index (2, 12, 2) (up to 1.3e-06 allowed)&#10;&#10;To execute this test, run the following from the base repo dir:&#10;    PYTORCH_TEST_WITH_SLOW=1 python test/distributed/tensor/parallel/test_tp_style.py TensorParallelStyleTest.test_sequence_parallel_style&#10;&#10;This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0">Traceback (most recent call last):
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 716, in wrapper
    self._join_processes(fn)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 980, in _join_processes
    self._check_return_codes(fn, elapsed_time)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 1020, in _check_return_codes
    raise RuntimeError(error)
RuntimeError: Process 1 exited with error code 10 and exception:
Traceback (most recent call last):
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 864, in run_test
    getattr(self, test_name)()
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 718, in wrapper
    fn()
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 3226, in wrapper
    method(*args, **kwargs)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/distributed/_tensor/common_dtensor.py", line 491, in wrapper
    raise e
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/distributed/_tensor/common_dtensor.py", line 488, in wrapper
    func(self, *args, **kwargs)  # type: ignore[misc]
  File "/home/jenkins/actions-runner/_work/torch-xpu-ops/pytorch/test/distributed/tensor/parallel/test_tp_style.py", line 385, in test_sequence_parallel_style
    self.assertEqual(sharded_out.full_tensor(), output)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4181, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Tensor-likes are not close!

Mismatched elements: 3840 / 7680 (50.0%)
Greatest absolute difference: 3.7509000301361084 at index (13, 8, 0) (up to 1e-05 allowed)
Greatest relative difference: 3634.929931640625 at index (2, 12, 2) (up to 1.3e-06 allowed)

To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_SLOW=1 python test/distributed/tensor/parallel/test_tp_style.py TensorParallelStyleTest.test_sequence_parallel_style

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

Process 2 exited with error code 10 and exception:
Traceback (most recent call last):
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 864, in run_test
    getattr(self, test_name)()
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 718, in wrapper
    fn()
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 3226, in wrapper
    method(*args, **kwargs)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/distributed/_tensor/common_dtensor.py", line 491, in wrapper
    raise e
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/distributed/_tensor/common_dtensor.py", line 488, in wrapper
    func(self, *args, **kwargs)  # type: ignore[misc]
  File "/home/jenkins/actions-runner/_work/torch-xpu-ops/pytorch/test/distributed/tensor/parallel/test_tp_style.py", line 385, in test_sequence_parallel_style
    self.assertEqual(sharded_out.full_tensor(), output)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4181, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Tensor-likes are not close!

Mismatched elements: 3840 / 7680 (50.0%)
Greatest absolute difference: 3.7509000301361084 at index (13, 8, 0) (up to 1e-05 allowed)
Greatest relative difference: 3634.929931640625 at index (2, 12, 2) (up to 1.3e-06 allowed)

To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_SLOW=1 python test/distributed/tensor/parallel/test_tp_style.py TensorParallelStyleTest.test_sequence_parallel_style

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

Process 3 exited with error code 10 and exception:
Traceback (most recent call last):
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 864, in run_test
    getattr(self, test_name)()
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 718, in wrapper
    fn()
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 3226, in wrapper
    method(*args, **kwargs)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/distributed/_tensor/common_dtensor.py", line 491, in wrapper
    raise e
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/distributed/_tensor/common_dtensor.py", line 488, in wrapper
    func(self, *args, **kwargs)  # type: ignore[misc]
  File "/home/jenkins/actions-runner/_work/torch-xpu-ops/pytorch/test/distributed/tensor/parallel/test_tp_style.py", line 385, in test_sequence_parallel_style
    self.assertEqual(sharded_out.full_tensor(), output)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4181, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Tensor-likes are not close!

Mismatched elements: 3840 / 7680 (50.0%)
Greatest absolute difference: 3.7509000301361084 at index (13, 8, 0) (up to 1e-05 allowed)
Greatest relative difference: 3634.929931640625 at index (2, 12, 2) (up to 1.3e-06 allowed)

To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_SLOW=1 python test/distributed/tensor/parallel/test_tp_style.py TensorParallelStyleTest.test_sequence_parallel_style

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0</failure></testcase></testsuite></testsuites>